import google.generativeai as genai
from app.config.settings import settings

genai.configure(api_key=settings.GEMINI_API_KEY)

def generate_insights(context_data):
    """
    Generate business insights and analysis using Google's Gemini AI model.

    This function leverages Google's Gemini Pro language model to analyze business
    data and generate executive-level insights. It takes structured data context
    (typically including sample data and statistical summaries) and processes it
    through AI to identify patterns, trends, and actionable intelligence. The
    function returns insights in a structured JSON format that includes three
    key insights and an overall assessment score, making it suitable for
    automated reporting and business intelligence applications.

    The AI analysis focuses on extracting meaningful business intelligence from
    the provided data context, identifying significant patterns, potential risks,
    opportunities, and strategic recommendations. The structured output format
    ensures consistency and facilitates integration with downstream reporting
    systems and dashboards.

    Args:
        context_data (str): Formatted string containing the data context to analyze.
                           This should include both sample data (first few rows)
                           and statistical summaries in a human-readable format.
                           The context_data is typically generated by the
                           prepare_context_for_ai function and contains sufficient
                           information for the AI to understand data patterns
                           and characteristics.

    Returns:
        str: JSON-formatted string containing the AI-generated insights with the
             following structure:
             
             {
                 "insight_1": "First key business insight based on the data",
                 "insight_2": "Second key business insight based on the data", 
                 "insight_3": "Third key business insight based on the data",
                 "overall_score": "Numerical score from 0-100 assessing data quality/significance"
             }
             
             The returned string contains the raw AI response which should be
             parsed as JSON by calling functions to extract individual insights.

    Raises:
        google.generativeai.types.generation_types.BlockedPromptException: If the input
            contains content that violates AI safety guidelines
        google.generativeai.types.generation_types.StopCandidateException: If the
            generation is stopped due to safety filters
        requests.exceptions.RequestException: If there are network connectivity issues
            when communicating with the Gemini API
        google.api_core.exceptions.GoogleAPICallError: If the API call fails due to
            authentication, quota limits, or other Google Cloud service errors

    Example:
        context = "Data Head:\\n   revenue  users\\n0   1000    100\\n1   1500    150\\n...\\n\\nStatistics:\\n{'revenue': {'mean': 1250}}"
        
        insights_json = generate_insights(context)
        import json
        insights = json.loads(insights_json)
        print(f"Primary insight: {insights['insight_1']}")
        print(f"Quality score: {insights['overall_score']}")
    """
    model = genai.GenerativeModel('gemini-pro')

    prompt = f"""
    Analyze the following business data summary and provide 3 key executive insights.
    Format as JSON with keys: insight_1, insight_2, insight_3, overall_score (0-100).

    {context_data}
    """

    response = model.generate_content(prompt)
    return response.text